<?php

namespace ContainerCfk7VgR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLecturaCSVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\LecturaCSV' shared autowired service.
     *
     * @return \App\Service\LecturaCSV
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'LecturaCSV.php';

        return $container->services['App\\Service\\LecturaCSV'] = new \App\Service\LecturaCSV();
    }
}
