# services.yaml

parameters:
    env(MONGODB_URL): 'mongodb://julian:k6OFfWzFkrK4Df3Z@proyecto.nwum4.mongodb.net/?retryWrites=true&w=majority&appName=proyecto'
    env(MONGODB_DB): 'proyecto'

services:
    App\Service\FacturaService:
        autowire: true
        autoconfigure: true
        public: true
        arguments:
            $documentManager: '@doctrine_mongodb.odm.document_manager'

    App\Service\UsuarioService:
        autowire: true
        autoconfigure: true
        public: true
        arguments:
            $documentManager: '@doctrine_mongodb.odm.document_manager'

    App\Service\ProductoService:
        autowire: true
        autoconfigure: true
        public: true
        arguments:
            $documentManager: '@doctrine_mongodb.odm.document_manager'

    App\Controller\LecturaCsvController:
        autowire: true
        autoconfigure: true
        public: true

    Kreait\Firebase\Factory:
        arguments:
            - '%kernel.project_dir%/config/firebase_credentials.json'
        tags: ['firebase']

    # Configuración del servicio `LecturaCSV`
    App\Service\LecturaCSV:
        autowire: true
        autoconfigure: true
        public: true

    # Configuración para los controladores
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    _defaults:
        autowire: true
        autoconfigure: true
