<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Hydrator\HydratorException;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppDocumentProductoHydrator implements HydratorInterface
{
    private $dm;
    private $class;

    public function __construct(DocumentManager $dm, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->class = $class;
    }

    public function hydrate(object $document, array $data, array $hints = array()): array
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = $value instanceof \MongoDB\BSON\ObjectId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['nombre']) || (! empty($this->class->fieldMappings['nombre']['nullable']) && array_key_exists('nombre', $data))) {
            $value = $data['nombre'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['nombre']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['nombre']->setValue($document, $return);
            $hydratedData['nombre'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['precio']) || (! empty($this->class->fieldMappings['precio']['nullable']) && array_key_exists('precio', $data))) {
            $value = $data['precio'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['precio']['type'];
                $return = (float) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['precio']->setValue($document, $return);
            $hydratedData['precio'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['marca']) || (! empty($this->class->fieldMappings['marca']['nullable']) && array_key_exists('marca', $data))) {
            $value = $data['marca'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['marca']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['marca']->setValue($document, $return);
            $hydratedData['marca'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['cantidad']) || (! empty($this->class->fieldMappings['cantidad']['nullable']) && array_key_exists('cantidad', $data))) {
            $value = $data['cantidad'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['cantidad']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['cantidad']->setValue($document, $return);
            $hydratedData['cantidad'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['descripcion']) || (! empty($this->class->fieldMappings['descripcion']['nullable']) && array_key_exists('descripcion', $data))) {
            $value = $data['descripcion'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['descripcion']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['descripcion']->setValue($document, $return);
            $hydratedData['descripcion'] = $return;
        }
        return $hydratedData;
    }
}