<?php

namespace ContainerTx1E5aD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFacturaServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\FacturaService' shared autowired service.
     *
     * @return \App\Service\FacturaService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'FacturaService.php';

        return $container->services['App\\Service\\FacturaService'] = new \App\Service\FacturaService(($container->services['doctrine_mongodb.odm.default_document_manager'] ?? $container->load('getDoctrineMongodb_Odm_DefaultDocumentManagerService')), ($container->services['App\\Service\\ProductoService'] ?? $container->load('getProductoServiceService')));
    }
}
