<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTx1E5aD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTx1E5aD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTx1E5aD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTx1E5aD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTx1E5aD\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tx1E5aD',
    'container.build_id' => 'f798dfe2',
    'container.build_time' => 1725994464,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTx1E5aD');
