<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFcE3FF4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFcE3FF4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFcE3FF4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFcE3FF4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFcE3FF4\App_KernelDevDebugContainer([
    'container.build_hash' => 'FcE3FF4',
    'container.build_id' => 'c9c0c71e',
    'container.build_time' => 1725498898,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFcE3FF4');
